. /home/502/aph502/code/bash/demo-magic/demo-magic.sh
DEMO_PROMPT="[03 \W]$ "
cd data-shell &> /dev/null
clear
pe 'whoami'
pe 'groups'
pe 'finger aidan'
pe 'time sleep 5'
pe 'time find . | wc -l'
pe 'time find . | wc -l'
pe 'which time'
pe '/usr/bin/time ls'
pe 'type time'
pe '/usr/bin/time -v find . | wc -l'
pe 'file pizza.cfg '
pe 'file solar.pdf'
p '# New slide'
pe 'du -shc'
pe 'du -shc molecules'
pe 'du -shc molecules/*'
pe 'echo du -shc molecules/*'
pe 'ls -lSrh molecules/*'
pe 'ls -lSrhd writing/*'
pe 'du -shc writing/*'
pe 'du -shc writing/* | sort -h'
pe 'for d in *; do echo -n $(find $d | wc -l); echo " $d"; done | sort -h'
pe 'df -h'
p '# New slide'
pe 'ls -l pizza.cfg'
pe 'chmod g-r pizza.cfg'
pe 'ls -l pizza.cfg'
pe 'mkdir tmp'
pe 'touch tmp/a_single_file'
pe 'chmod u-r tmp'
pe 'ls -ld tmp'
pe 'ls -l tmp'
pe 'chmod u+r tmp'
pe 'chmod a-x tmp'
pe 'ls -ld tmp'
pe 'cd tmp'
pe 'ls -l tmp'
pe 'chmod a+x tmp'
pe 'touch tmp/file1 tmp/file2 tmp/file3'
pe 'chgrp hh5 tmp/file1'
pe 'ls -l tmp'
pe 'chgrp -R hh5 tmp'
pe 'ls -l tmp'
pe 'touch tmp/newfile'
pe 'ls -l tmp/newfile'
pe 'chmod g+s tmp'
pe 'touch tmp/evennewerfile'
pe 'ls -l tmp/evennewerfile'
pe 'chmod -R o+rX tmp'
pe 'getfacl log'
pe 'setfacl -m g:hh5:r log'
pe 'getfacl log'
pe 'mkdir shared'
pe 'setfacl -R -m u:saw562:rwX shared'
pe 'setfacl -R -d -m u:saw562:rwX shared '  
pe 'setfacl -R -d -m u:aph502:rwX shared'
pe 'getfacl shared'
pe 'touch shared/newsharedfile'
pe 'getfacl shared/newsharedfile'
pe 'ln -s north-pacific-gyre/2012-07-03/goostats statslink'
pe 'ls -l'
pe 'rm statslink'
pe 'ln north-pacific-gyre/2012-07-03/goostats statslink'
pe 'ls -l'
pe 'rm statslink'
p '# New slide'
pe 'module load pbs'
pe 'module show pbs'
pe 'module unload pbs'
pe 'module list'
module unuse ~access/modules
pe 'module avail nccompress'
pe 'module use ~access/modules'
pe 'module avail nccompress'
pe 'module purge'
pe 'module list'
